spring:
  application:
    name: stock_price_notification_service

server:
  error:
    include-message: always

aws:
  region: us-east-2

dynamodb:
  table-name: StockAlertsTable
  region: us-east-2

finnhub:
  api-key: ${FINNHUB_API_KEY}
  base-url: https://finnhub.io/api/v1