spring:
  application:
    name: stock_alert_service

server:
  error:
    include-message: always

aws:
  region: us-east-2

dynamodb:
  table-name: StockAlertsTable
  region: us-east-2

finnhub:
  api-key: ${FINNHUB_API_KEY}
  base-url: https://finnhub.io/api/v1

scheduler:
  secret-key: ${SCHEDULER_SECRET_KEY}
