spring:
  application:
    name: stock_alert_service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLCLIENTID}
            client-secret: ${GOOGLSECRET}
            scope:
              - email
              - profile

server:
  error:
    include-message: always

aws:
  region: us-east-2

dynamodb:
  table-name: StockAlertsTable
  user-table-name: UsersTable
  region: us-east-2

finnhub:
  api-key: ${FINNHUB_API_KEY}
  base-url: https://finnhub.io/api/v1

scheduler:
  secret-key: ${SCHEDULER_SECRET_KEY}

